# Dynamic Category Configuration for Sitemap Analyzer
# This file defines all classification categories used by the zero-shot classifier
# Administrators can modify these categories without changing code

categories:
  # Primary page type classification
  primary_type:
    - homepage
    - product page
    - category page
    - blog post
    - article
    - landing page
    - contact page
    - about page
    - FAQ page
    - documentation
    - portfolio
    - gallery
    - search results
    - user profile
    - checkout page
    - login page
    - registration page
    - dashboard
    - settings page
    - 404 error page

  # Content category classification
  content_category:
    - e-commerce
    - blog
    - news
    - educational
    - entertainment
    - corporate
    - personal
    - portfolio
    - community
    - support
    - documentation
    - marketing
    - social media
    - forum
    - wiki
    - government
    - non-profit
    - healthcare
    - finance
    - technology

  # User intent classification
  intent:
    - informational
    - navigational
    - transactional
    - commercial investigation
    - local
    - support
    - entertainment
    - social interaction
    - account management
    - content creation
    - research
    - comparison shopping

  # Industry/vertical classification
  industry:
    - retail
    - technology
    - healthcare
    - finance
    - education
    - entertainment
    - travel
    - real estate
    - automotive
    - food and beverage
    - fashion
    - sports
    - media
    - software
    - consulting
    - manufacturing
    - telecommunications
    - energy
    - agriculture
    - hospitality

  # Audience type classification
  audience:
    - B2B (business-to-business)
    - B2C (business-to-consumer)
    - B2G (business-to-government)
    - C2C (consumer-to-consumer)
    - general public
    - professionals
    - students
    - developers
    - researchers
    - enterprise
    - small business
    - hobbyists

  # Content format classification
  format:
    - text article
    - video content
    - image gallery
    - interactive tool
    - downloadable resource
    - form
    - calculator
    - quiz
    - survey
    - map
    - chart/graph
    - infographic
    - podcast
    - webinar
    - course/tutorial

  # Engagement level classification
  engagement:
    - high engagement (interactive)
    - medium engagement (mixed content)
    - low engagement (static content)
    - passive consumption
    - active participation
    - community driven
    - user generated content

  # SEO priority classification
  seo_priority:
    - critical (homepage, main categories)
    - high (top products, key content)
    - medium (supporting pages)
    - low (utility pages)
    - minimal (legal, privacy)
    - noindex recommended

# Metadata
config_version: "1.0"
last_updated: "2025-10-24"
description: "Default category configuration for sitemap URL classification"
